[project]
dynamic = ["version"]
name = "janaf"
description = "Python wrapper for NIST-JANAF Thermochemical Tables"
readme = "README.md"
requires-python = ">=3.10"
license = "0BSD"
authors = [
  { name = "Takumasa Nakamura", email = "n.takumasa@gmail.com" },
]
classifiers = [
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.15",
  "Programming Language :: Python :: Implementation :: CPython",
  "Topic :: Scientific/Engineering :: Chemistry",
  "Topic :: Scientific/Engineering :: Physics",
]
urls.Repository = "https://github.com/n-takumasa/py-janaf"

dependencies = [
  "polars>=1.35.2",
]

[project.optional-dependencies]
xarray = [
  "xarray>=2024.9.0",
]
all = ["janaf[xarray]"]

[dependency-groups]
optional = [
  # "janaf[all]",
  "xarray>=2024.9.0",
]
dev = [
  { include-group = "optional" },
  "tox>=4.22",
  "tox-uv",
  { include-group = "docs" },
  { include-group = "lint" },
  { include-group = "script" },
  { include-group = "test" },
  { include-group = "type_ty" },
]
lint = ["ruff"]
script = ["aiofiles", "aiohttp"]
docs = [
  "mkdocstrings-python>=1.11.1",
  "zensical>=0.0.21",
]
test-base = [
  "pytest>=9.1.1",
  "pytest-cov>=7.1.0",
  "pytest-github-actions-annotate-failures>=0.4.2",
]
test = [
  { include-group = "optional" },
  "matplotlib>=3.10.5",
  "pint-xarray>=0.5.1",
  { include-group = "test-base" },
]
test-minimal = [
  { include-group = "test-base" },
]
type_ty = [
  "ty>=0.0.2",
  { include-group = "script" },
  { include-group = "test" },
]
type_mypy = [
  "mypy[install-types]",
  { include-group = "script" },
  { include-group = "test" },
]

[tool.uv.dependency-groups]
dev = { requires-python = ">=3.13" }
docs = { requires-python = ">=3.13" }

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch]
version.source = "vcs"
build.hooks.vcs.version-file = "src/janaf/_version.py"
build.targets.sdist.exclude = [
  "/.github",
  "scripts/",
]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests", "src", "README.md"]
log_level = "INFO"
xfail_strict = true
addopts = [
  "-ra",
  "--strict-config",
  "--strict-markers",
  "-p", "no:faulthandler",  # TODO: pola-rs/polars#23142
  "--doctest-modules",
  "--doctest-glob", "*.md",
]
filterwarnings = [
  "error",
  # TODO: n-takumasa/py-janaf#54
  "ignore:In Polars 2.0, the default behavior for `empty_as_null`:DeprecationWarning",
  "ignore:The 'generic' unit for NumPy timedelta is deprecated:DeprecationWarning",
]

[tool.coverage]
run.source_pkgs = ["janaf", "tests"]
run.branch = true
run.parallel = true
report.exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
  "@overload",
]

[tool.ruff]
line-length = 88

[tool.ruff.format]
preview = false
docstring-code-format = true

[tool.ruff.lint]
preview = true
pydocstyle.convention = "numpy"
extend-select = ["ALL"]
ignore = [
  # https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
  "W191", "E111", "E114", "E117", "D206", "D300",
  "Q000", "Q001", "Q002", "COM812", "COM819", "E501",
  #
  "D100",  # undocumented-public-module
  "D104",  # undocumented-public-package
  "FIX002",  # line-contains-todo
  "PLC0415",  # import-outside-top-level
  "RET504",  # unnecessary-assign
  "TD002",  # missing-todo-author
  #
  "CPY001",  # missing-copyright-notice
  "PLC1901",  # compare-to-empty-string
  "RUF067",  # non-empty-init-module
]
extend-per-file-ignores."example/**.py" = [
  "D100",
]
extend-per-file-ignores."scripts/**.py" = [
  "D100", "D103", "INP001", "LOG015", "PTH123", "S101", 
]
extend-per-file-ignores."tests/**.py" = [
  "ANN201", "D100", "D103", "ICN001", "PTH123", "PLR2004", "S101", 
]

[tool.mypy]
files = "src,scripts,example"
strict = true
warn_unreachable = true
enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]

[tool.tox]
requires = [
  "tox>=4.21",
  "tox-uv",
]
env_list = [
  "lint", "type_ty", "type_mypy",
  "3.15-minimal",
  "3.14", "3.14-minimal", "3.14-lowest",
  "3.10", "3.10-minimal", "3.10-lowest",
]

[tool.tox.gh.python]
"3.15" = ["3.15-minimal"]
"3.14" = ["3.14", "3.14-minimal", "3.14-lowest"]
"3.10" = ["3.10", "3.10-minimal", "3.10-lowest"]

[tool.tox.env_run_base]
labels = ["test"]
package = "wheel"
wheel_build_env = ".pkg"
dependency_groups = [
  { replace = "if", condition = "factor.minimal", then = "test-minimal", "else" = "test" },
]
commands = [
  ["pytest", { replace = "posargs", default = [], extend = true }],
]
set_env.PY_IGNORE_IMPORTMISMATCH = "1"  # pytest-dev/pytest#9567
set_env.UV_RESOLUTION = { replace = "if", condition = "factor.lowest", then = "lowest-direct", "else" = "highest" }
set_env.ALLOW_MISSING_DEPS = { replace = "if", condition = "factor.minimal", then = "1", "else" = "0" }
pass_env = [
  "GITHUB_ACTIONS",
]

[tool.tox.env.docs]
labels = ["docs"]
dependency_groups = ["docs"]
commands = [
  ["zensical", { replace = "posargs", default = ["build", "--clean"], extend = true }],
]

[tool.tox.env.lint]
labels = ["static"]
package = "skip"
deps = [
  "ruff",
]
commands = [
  ["ruff", "format", "--check", { replace = "posargs", default = [], extend = true }],
  ["ruff", "check", "--no-fix", { replace = "posargs", default = [], extend = true }],
]
pass_env = [
  "RUFF_OUTPUT_FORMAT",
]

[tool.tox.env.type_ty]
labels = ["static"]
package = "skip"
dependency_groups = ["type_ty"]
commands = [
  ["ty", "check", { replace = "posargs", default = [], extend = true }],
]

[tool.tox.env.type_mypy]
labels = ["static"]
package = "skip"
dependency_groups = ["type_mypy"]
commands = [
  ["mypy", "--install-types", "--non-interactive", { replace = "posargs", default = [], extend = true }],
]
