# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: ${{ matrix.session }} ${{ matrix.python }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python: "3.12", os: "ubuntu-latest", session: "tests" }
          - { python: "3.11", os: "ubuntu-latest", session: "tests" }
          - { python: "3.10", os: "ubuntu-latest", session: "tests" }
          - { python: "3.9", os: "ubuntu-latest", session: "tests" }

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install poetry
        run: |
          pipx install poetry
      - name: Install nox
        run: |
          pipx install nox
      - name: install nox-poetry
        run: |
          pipx inject poetry poetry-dynamic-versioning[plugin]
      - name: Install dependencies
        run: |
          poetry install
      - name: Run nox
        run: |
          nox --session=${{ matrix.session }} --python=${{ matrix.python }}
