name: test

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"
  RUFF_OUTPUT_FORMAT: "github"
  CI_BASE_PYTHON: "3.14"

jobs:
  static:
    name: static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d  # v10.0.0
        with:
          enable-cache: false
      - name: Install tox
        run: >-
          uv tool install
          --python-preference only-managed
          --python ${{ env.CI_BASE_PYTHON }}
          tox
          --with tox-uv
      - run: tox -m static
  run:
    name: test with ${{ matrix.env }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        env: ["3.15", "3.14", "3.10"]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d  # v10.0.0
        with:
          enable-cache: false
      - name: Install tox
        run: >-
          uv tool install
          --python-preference only-managed
          --python ${{ env.CI_BASE_PYTHON }}
          tox
          --with tox-uv
          --with tox-gh
      - name: Install Python
        if: matrix.env != env.CI_BASE_PYTHON
        run: >-
          uv python install
          --python-preference only-managed
          ${{ matrix.env }}
      - name: Setup test suite
        run: tox run -vv --notest --skip-missing-interpreters false
        env:
          TOX_GH_MAJOR_MINOR: ${{ matrix.env }}
      - name: Run test suite
        run: tox run --skip-pkg-install
        env:
          TOX_GH_MAJOR_MINOR: ${{ matrix.env }}
